/**:
  ros__parameters:
    robot_base_frame: Robot
    return_to_init: false
    costmap_topic: merged_map
    costmap_updates_topic: map_updates
    visualize: true
    planner_frequency: 0.15
    progress_timeout: 30.0
    potential_scale: 50.0
    orientation_scale: 0.0
    gain_scale: 0.05
    transform_tolerance: 0.3
    min_frontier_size: 0.75